In [182]:
import math
import numpy as np
import pandas as pd
import scipy
import seaborn as sn
sn.set(rc={'figure.figsize':(11, 4)})

from scipy import stats, optimize
from scipy.stats import genextreme
import matplotlib
import matplotlib.pyplot as plt
import scipy.stats
from sklearn import svm
from sklearn.preprocessing import MinMaxScaler
%matplotlib notebook

%run oneG_trim.ipynb

In [183]:
data = pd.read_csv('cs1_L95.csv')

In [184]:
from datetime import date

In [185]:
data = data.assign(Date=pd.to_datetime(data[['year', 'month','day']]))

In [186]:
data.drop(data.columns[[0,2,3,4,5,6]], axis=1, inplace=True)

In [187]:
data = data.set_index('Date')

In [188]:
data

runoff_obs  precip  tmax  tmin
Date                                      
2002-10-01         2.7    0.13  57.4  34.6
2002-10-02         2.7    0.97  38.4  29.7
2002-10-03         2.8    0.04  41.2  31.7
2002-10-04         2.8    0.00  52.9  34.0
2002-10-05         2.6    0.00  50.5  34.8
...                ...     ...   ...   ...
2012-09-26         4.4    0.00  59.2  41.0
2012-09-27         4.3    0.00  64.1  43.2
2012-09-28         4.2    0.00  68.0  46.2
2012-09-29         4.2    0.00  69.8  50.9
2012-09-30         4.1    0.00  72.8  52.0

[3465 rows x 4 columns]

In [189]:
data_values = data.values
features = data_values[:,1:]
values = data_values[:,0]

In [190]:
from sklearn.model_selection import train_test_split

In [191]:
X_train, X_test, Y_train, Y_test = train_test_split(features, values,test_size=0.3)

In [192]:
arr = []


In [193]:
arr.append(X_train)

In [194]:
arr

[array([[0.00e+00, 5.18e+01, 3.14e+01],
        [5.00e-02, 4.27e+01, 3.11e+01],
        [0.00e+00, 6.74e+01, 3.67e+01],
        ...,
        [0.00e+00, 5.06e+01, 2.58e+01],
        [0.00e+00, 6.50e+01, 4.23e+01],
        [0.00e+00, 7.15e+01, 4.36e+01]])]

In [195]:
arr.extend(x_train)

In [196]:
arr

[array([[0.00e+00, 5.18e+01, 3.14e+01],
        [5.00e-02, 4.27e+01, 3.11e+01],
        [0.00e+00, 6.74e+01, 3.67e+01],
        ...,
        [0.00e+00, 5.06e+01, 2.58e+01],
        [0.00e+00, 6.50e+01, 4.23e+01],
        [0.00e+00, 7.15e+01, 4.36e+01]]),
 array([ 0. , 84.4, 61.1]),
 array([1.00e-02, 7.05e+01, 4.47e+01]),
 array([ 0. , 61.6, 38.1]),
 array([ 0. , 72.3, 47.6]),
 array([ 0. , 86.4, 55.2]),
 array([ 0. , 77.7, 46.6]),
 array([ 0. , 71.9, 44.7]),
 array([ 0. , 77.8, 51.8]),
 array([ 0. , 77.2, 54.8]),
 array([ 0.1, 82.4, 58.5]),
 array([ 0. , 77.4, 51.8]),
 array([ 0.08, 70.1 , 47.5 ]),
 array([ 0.11, 73.7 , 56.  ]),
 array([ 0. , 83.7, 59.4]),
 array([ 0. , 81.2, 57.6]),
 array([ 0. , 92.9, 68.6]),
 array([ 0. , 82. , 51.3]),
 array([ 0. , 77.8, 51.3]),
 array([ 0. , 82.9, 61. ]),
 array([ 0. , 84.7, 53.3]),
 array([ 0. , 77.8, 53.7]),
 array([5.00e-02, 5.53e+01, 3.03e+01]),
 array([4.00e-02, 4.91e+01, 2.83e+01]),
 array([ 0. , 80.7, 57.2]),
 array([ 0. , 80.3, 51.9]),
 ar